# === DATABASE CONNECTION ===
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_budget_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# === HIBERNATE / JPA ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# === SQL LOGGING (DEV) ===
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === CONNECTION POOL (Hikari) ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# === TIMEZONE ===
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# = SERVER
server.port=8080

# === KAFKA CONFIG (budget-compose: Redpanda on localhost:9093) ===
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.admin.fail-fast=false

# Disable Redis session until Redis is configured
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,\
  org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

# Topics
app.kafka.topic.transactions=transactions
